PART A. Importing the Needed Modules from in-class tutorial

In [10]:
import numpy as np

from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV

from keras.layers import Dense, Dropout, Activation, Flatten
from keras.models import Sequential
from keras.utils import np_utils


PART B. Import mnist and split and reshape

In [13]:
from keras.datasets import mnist

(X_train, y_train), (X_test, y_test) = mnist.load_data()
X_train = X_train.reshape(X_train.shape[0], 784)
X_test = X_test.reshape(X_test.shape[0], 784)

In [14]:
print(X_train.shape)
print(X_test.shape)

(60000, 784)
(10000, 784)


In [20]:
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255

PART C. OneHotEncoding on label y

In [18]:
y_train = np_utils.to_categorical(y_train, 10)
y_test = np_utils.to_categorical(y_test, 10)

In [21]:
print (y_train.shape)
print (y_train[:10,:])

(60000, 10)
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


PART D. Define model_creator function

In [31]:
def model_creator():
    # define:
    model = Sequential()
    # design the structure:
    model.add(Dense(hidden_neurons, input_dim = input_size))
    model.add(Activation('sigmoid')) # Activation
    
    model.add(Dense(out_size, input_dim = hidden_neurons))  # Nuerons
    model.add(Activation('softmax')) # Activation
    # compile:
    model.compile(loss='categorical_crossentropy', optimizer='adam',
    metrics=['accuracy'])
    # return:
    return model 

PART E. Fixing the random state

In [32]:
seed = 2
np.random.seed(seed)

PART F. Wrapmodel as an Object using KerasClassifier

In [33]:
model = KerasClassifier(build_fn=model_creator,verbose=2)

PART G. Using sklearn GridSearch

In [34]:
batch_size = [30,50,100]
epochs = [10,15,20]

NameError: name 'hidden_neurons' is not defined