PART A. Importing the Needed Modules from in-class tutorial

In [102]:
import numpy as np

from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV

from keras.layers import Dense, Dropout, Activation, Flatten
from keras.models import Sequential
from keras.utils import np_utils

from sklearn.metrics import accuracy_score
from sklearn.metrics import log_loss

PART B. Import mnist and split and reshape

In [2]:
from keras.datasets import mnist

#loading the data from mnist and reshaping it
(X_train, y_train), (X_test, y_test) = mnist.load_data()
X_train = X_train.reshape(X_train.shape[0], 784)
X_test = X_test.reshape(X_test.shape[0], 784)

In [3]:
print(X_train.shape)
print(X_test.shape)

(60000, 784)
(10000, 784)


In [4]:
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255

PART C. OneHotEncoding on label y

In [5]:
y_train = np_utils.to_categorical(y_train, 10)
y_test = np_utils.to_categorical(y_test, 10)

In [6]:
print (y_train.shape)
print (y_train[:10,:])

(60000, 10)
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


PART D. Define model_creator function

In [14]:
input_size = 784
hidden_neurons = 100
out_size = 10
def model_creator():
   
    # define:
    model = Sequential()
    # design the structure:
    model.add(Dense(hidden_neurons, input_dim = input_size))
    model.add(Activation('sigmoid')) # Activation
    
    model.add(Dense(out_size, input_dim = hidden_neurons))  # Nuerons
    model.add(Activation('softmax')) # Activation
    # compile:
    model.compile(loss='categorical_crossentropy', optimizer='adam',
    metrics=['accuracy'])
    # return:
    return model 

PART E. Fixing the random state

In [15]:
seed = 2
np.random.seed(seed)

PART F. Wrapmodel as an Object using KerasClassifier

In [16]:
model = KerasClassifier(build_fn=model_creator,verbose=2)

PART G. Using sklearn GridSearch

In [17]:
# batch_size = [30,50,100]
# epochs = [10,15,20]

In [26]:
epochs = np.array([10 , 15 , 20])
batches = np.array([30 , 50 , 100])
param_grid = dict(epochs=epochs, batch_size=batches)
grid = GridSearchCV(estimator=model, param_grid=param_grid, scoring='neg_log_loss', cv=10)

In [27]:
grid_result = grid.fit(X_train, y_train, verbose=1)

Epoch 1/10
54000/54000 [==============================] - 9s 161us/step - loss: 0.4432 - acc: 0.8860
Epoch 2/10
54000/54000 [==============================] - 6s 116us/step - loss: 0.2093 - acc: 0.9399
Epoch 3/10
54000/54000 [==============================] - 6s 116us/step - loss: 0.1553 - acc: 0.9553
Epoch 4/10
54000/54000 [==============================] - 6s 116us/step - loss: 0.1230 - acc: 0.9646
Epoch 5/10
54000/54000 [==============================] - 6s 115us/step - loss: 0.1007 - acc: 0.9712
Epoch 6/10
54000/54000 [==============================] - 6s 118us/step - loss: 0.0835 - acc: 0.9764
Epoch 7/10
54000/54000 [==============================] - 6s 116us/step - loss: 0.0700 - acc: 0.9804
Epoch 8/10
54000/54000 [==============================] - 6s 117us/step - loss: 0.0593 - acc: 0.9837
Epoch 9/10
54000/54000 [==============================] - 6s 116us/step - loss: 0.0506 - acc: 0.9864
Epoch 10/10
54000/54000 [==============================] - 6s 116us/step - loss: 0.0431 - a

54000/54000 [==============================] - 7s 121us/step - loss: 0.2086 - acc: 0.9412
Epoch 3/10
54000/54000 [==============================] - 7s 125us/step - loss: 0.1559 - acc: 0.9552
Epoch 4/10
54000/54000 [==============================] - 7s 124us/step - loss: 0.1247 - acc: 0.9644
Epoch 5/10
54000/54000 [==============================] - 7s 123us/step - loss: 0.1021 - acc: 0.9710
Epoch 6/10
54000/54000 [==============================] - 7s 123us/step - loss: 0.0856 - acc: 0.9764
Epoch 7/10
54000/54000 [==============================] - 7s 125us/step - loss: 0.0735 - acc: 0.9792
Epoch 8/10
54000/54000 [==============================] - 7s 123us/step - loss: 0.0622 - acc: 0.9826
Epoch 9/10
54000/54000 [==============================] - 7s 124us/step - loss: 0.0539 - acc: 0.9853
Epoch 10/10
54000/54000 [==============================] - 7s 123us/step - loss: 0.0469 - acc: 0.9879
Epoch 1/10
54000/54000 [==============================] - 9s 172us/step - loss: 0.4394 - acc: 0.8882


54000/54000 [==============================] - 7s 128us/step - loss: 0.2107 - acc: 0.9398
Epoch 3/15
54000/54000 [==============================] - 7s 128us/step - loss: 0.1571 - acc: 0.9555
Epoch 4/15
54000/54000 [==============================] - 7s 130us/step - loss: 0.1245 - acc: 0.9647
Epoch 5/15
54000/54000 [==============================] - 7s 130us/step - loss: 0.1011 - acc: 0.9714
Epoch 6/15
54000/54000 [==============================] - 7s 128us/step - loss: 0.0842 - acc: 0.9765
Epoch 7/15
54000/54000 [==============================] - 7s 128us/step - loss: 0.0712 - acc: 0.9801
Epoch 8/15
54000/54000 [==============================] - 7s 131us/step - loss: 0.0608 - acc: 0.9830
Epoch 9/15
54000/54000 [==============================] - 7s 129us/step - loss: 0.0517 - acc: 0.9856
Epoch 10/15
54000/54000 [==============================] - 7s 129us/step - loss: 0.0452 - acc: 0.9876
Epoch 11/15
54000/54000 [==============================] - 7s 129us/step - loss: 0.0382 - acc: 0.9906

54000/54000 [==============================] - 7s 137us/step - loss: 0.0738 - acc: 0.9792
Epoch 8/15
54000/54000 [==============================] - 8s 139us/step - loss: 0.0632 - acc: 0.9825
Epoch 9/15
54000/54000 [==============================] - 7s 137us/step - loss: 0.0540 - acc: 0.9855
Epoch 10/15
54000/54000 [==============================] - 7s 138us/step - loss: 0.0464 - acc: 0.9876
Epoch 11/15
54000/54000 [==============================] - 7s 138us/step - loss: 0.0400 - acc: 0.9899
Epoch 12/15
54000/54000 [==============================] - 8s 139us/step - loss: 0.0346 - acc: 0.9916
Epoch 13/15
54000/54000 [==============================] - 7s 137us/step - loss: 0.0298 - acc: 0.9933
Epoch 14/15
54000/54000 [==============================] - 7s 138us/step - loss: 0.0256 - acc: 0.9944
Epoch 15/15
54000/54000 [==============================] - 7s 138us/step - loss: 0.0224 - acc: 0.9956
Epoch 1/20
54000/54000 [==============================] - 10s 192us/step - loss: 0.4314 - acc: 0

54000/54000 [==============================] - 8s 141us/step - loss: 0.0340 - acc: 0.9921
Epoch 13/20
54000/54000 [==============================] - 8s 142us/step - loss: 0.0292 - acc: 0.9936
Epoch 14/20
54000/54000 [==============================] - 8s 142us/step - loss: 0.0248 - acc: 0.9947
Epoch 15/20
54000/54000 [==============================] - 8s 145us/step - loss: 0.0214 - acc: 0.9959
Epoch 16/20
54000/54000 [==============================] - 8s 142us/step - loss: 0.0183 - acc: 0.9966
Epoch 17/20
54000/54000 [==============================] - 8s 142us/step - loss: 0.0155 - acc: 0.9974
Epoch 18/20
54000/54000 [==============================] - 8s 144us/step - loss: 0.0133 - acc: 0.9978
Epoch 19/20
54000/54000 [==============================] - 8s 142us/step - loss: 0.0110 - acc: 0.9986
Epoch 20/20
54000/54000 [==============================] - 8s 142us/step - loss: 0.0093 - acc: 0.9989
Epoch 1/20
54000/54000 [==============================] - 11s 201us/step - loss: 0.4303 - acc:

54000/54000 [==============================] - 8s 145us/step - loss: 0.0336 - acc: 0.9915
Epoch 13/20
54000/54000 [==============================] - 8s 144us/step - loss: 0.0285 - acc: 0.9936
Epoch 14/20
54000/54000 [==============================] - 8s 146us/step - loss: 0.0246 - acc: 0.9949
Epoch 15/20
54000/54000 [==============================] - 8s 146us/step - loss: 0.0211 - acc: 0.9958
Epoch 16/20
54000/54000 [==============================] - 8s 145us/step - loss: 0.0182 - acc: 0.9966
Epoch 17/20
54000/54000 [==============================] - 8s 148us/step - loss: 0.0154 - acc: 0.9974
Epoch 18/20
54000/54000 [==============================] - 8s 150us/step - loss: 0.0135 - acc: 0.9978
Epoch 19/20
54000/54000 [==============================] - 8s 151us/step - loss: 0.0114 - acc: 0.9983
Epoch 20/20
54000/54000 [==============================] - 8s 141us/step - loss: 0.0095 - acc: 0.9988
Epoch 1/20
54000/54000 [==============================] - 11s 200us/step - loss: 0.4365 - acc:

54000/54000 [==============================] - 5s 92us/step - loss: 0.1848 - acc: 0.9481
Epoch 4/10
54000/54000 [==============================] - 5s 91us/step - loss: 0.1502 - acc: 0.9579
Epoch 5/10
54000/54000 [==============================] - 5s 91us/step - loss: 0.1253 - acc: 0.9647
Epoch 6/10
54000/54000 [==============================] - 5s 91us/step - loss: 0.1069 - acc: 0.9702
Epoch 7/10
54000/54000 [==============================] - 5s 91us/step - loss: 0.0919 - acc: 0.9742
Epoch 8/10
54000/54000 [==============================] - 5s 93us/step - loss: 0.0798 - acc: 0.9782
Epoch 9/10
54000/54000 [==============================] - 5s 91us/step - loss: 0.0702 - acc: 0.9808
Epoch 10/10
54000/54000 [==============================] - 5s 91us/step - loss: 0.0618 - acc: 0.9832
Epoch 1/10
54000/54000 [==============================] - 8s 152us/step - loss: 0.5000 - acc: 0.8781
Epoch 2/10
54000/54000 [==============================] - 5s 91us/step - loss: 0.2373 - acc: 0.9324
Epoch 3/1

54000/54000 [==============================] - 6s 118us/step - loss: 0.0360 - acc: 0.9913
Epoch 15/15
54000/54000 [==============================] - 5s 99us/step - loss: 0.0317 - acc: 0.9928
Epoch 1/15
54000/54000 [==============================] - 9s 164us/step - loss: 0.4984 - acc: 0.8783
Epoch 2/15
54000/54000 [==============================] - 5s 97us/step - loss: 0.2380 - acc: 0.9316
Epoch 3/15
54000/54000 [==============================] - 5s 97us/step - loss: 0.1830 - acc: 0.9483
Epoch 4/15
54000/54000 [==============================] - 5s 98us/step - loss: 0.1479 - acc: 0.9581
Epoch 5/15
54000/54000 [==============================] - 5s 98us/step - loss: 0.1236 - acc: 0.9646
Epoch 6/15
54000/54000 [==============================] - 6s 103us/step - loss: 0.1048 - acc: 0.9696
Epoch 7/15
54000/54000 [==============================] - 6s 104us/step - loss: 0.0896 - acc: 0.9751
Epoch 8/15
54000/54000 [==============================] - 6s 102us/step - loss: 0.0782 - acc: 0.9785
Epoch

Epoch 5/15
54000/54000 [==============================] - 5s 99us/step - loss: 0.1266 - acc: 0.9648
Epoch 6/15
54000/54000 [==============================] - 5s 100us/step - loss: 0.1084 - acc: 0.9699
Epoch 7/15
54000/54000 [==============================] - 5s 99us/step - loss: 0.0938 - acc: 0.9738
Epoch 8/15
54000/54000 [==============================] - 6s 104us/step - loss: 0.0820 - acc: 0.9772
Epoch 9/15
54000/54000 [==============================] - 6s 108us/step - loss: 0.0716 - acc: 0.9805
Epoch 10/15
54000/54000 [==============================] - 6s 107us/step - loss: 0.0628 - acc: 0.9833
Epoch 11/15
54000/54000 [==============================] - 6s 103us/step - loss: 0.0553 - acc: 0.9856
Epoch 12/15
54000/54000 [==============================] - 5s 101us/step - loss: 0.0488 - acc: 0.9872
Epoch 13/15
54000/54000 [==============================] - 5s 100us/step - loss: 0.0433 - acc: 0.9892
Epoch 14/15
54000/54000 [==============================] - 6s 108us/step - loss: 0.0384 -

54000/54000 [==============================] - 6s 107us/step - loss: 0.1243 - acc: 0.9646
Epoch 6/20
54000/54000 [==============================] - 6s 103us/step - loss: 0.1059 - acc: 0.9700
Epoch 7/20
54000/54000 [==============================] - 6s 105us/step - loss: 0.0912 - acc: 0.9741
Epoch 8/20
54000/54000 [==============================] - 6s 103us/step - loss: 0.0789 - acc: 0.9782
Epoch 9/20
54000/54000 [==============================] - 6s 102us/step - loss: 0.0694 - acc: 0.9806
Epoch 10/20
54000/54000 [==============================] - 6s 103us/step - loss: 0.0607 - acc: 0.9836
Epoch 11/20
54000/54000 [==============================] - 6s 103us/step - loss: 0.0535 - acc: 0.9856
Epoch 12/20
54000/54000 [==============================] - 6s 104us/step - loss: 0.0473 - acc: 0.9874
Epoch 13/20
54000/54000 [==============================] - 6s 103us/step - loss: 0.0420 - acc: 0.9893
Epoch 14/20
54000/54000 [==============================] - 6s 102us/step - loss: 0.0369 - acc: 0.9

54000/54000 [==============================] - 6s 103us/step - loss: 0.1238 - acc: 0.9641
Epoch 6/20
54000/54000 [==============================] - 6s 103us/step - loss: 0.1060 - acc: 0.9699
Epoch 7/20
54000/54000 [==============================] - 6s 118us/step - loss: 0.0920 - acc: 0.9741
Epoch 8/20
54000/54000 [==============================] - 7s 130us/step - loss: 0.0800 - acc: 0.9780
Epoch 9/20
54000/54000 [==============================] - 7s 124us/step - loss: 0.0704 - acc: 0.9807
Epoch 10/20
54000/54000 [==============================] - 7s 122us/step - loss: 0.0616 - acc: 0.9835
Epoch 11/20
54000/54000 [==============================] - 7s 128us/step - loss: 0.0545 - acc: 0.9852
Epoch 12/20
54000/54000 [==============================] - 6s 111us/step - loss: 0.0481 - acc: 0.9874
Epoch 13/20
54000/54000 [==============================] - 6s 106us/step - loss: 0.0425 - acc: 0.9890
Epoch 14/20
54000/54000 [==============================] - 6s 109us/step - loss: 0.0378 - acc: 0.9

54000/54000 [==============================] - 6s 105us/step - loss: 0.1272 - acc: 0.9639
Epoch 6/20
54000/54000 [==============================] - 6s 106us/step - loss: 0.1082 - acc: 0.9690
Epoch 7/20
54000/54000 [==============================] - 6s 105us/step - loss: 0.0936 - acc: 0.9735
Epoch 8/20
54000/54000 [==============================] - 6s 105us/step - loss: 0.0809 - acc: 0.9776
Epoch 9/20
54000/54000 [==============================] - 6s 105us/step - loss: 0.0712 - acc: 0.9800
Epoch 10/20
54000/54000 [==============================] - 6s 111us/step - loss: 0.0621 - acc: 0.9829
Epoch 11/20
54000/54000 [==============================] - 6s 115us/step - loss: 0.0547 - acc: 0.9853
Epoch 12/20
54000/54000 [==============================] - 6s 113us/step - loss: 0.0485 - acc: 0.9873
Epoch 13/20
54000/54000 [==============================] - 6s 111us/step - loss: 0.0427 - acc: 0.9890
Epoch 14/20
54000/54000 [==============================] - 6s 111us/step - loss: 0.0379 - acc: 0.9

54000/54000 [==============================] - 3s 61us/step - loss: 0.1610 - acc: 0.9541
Epoch 6/10
54000/54000 [==============================] - 3s 61us/step - loss: 0.1402 - acc: 0.9601
Epoch 7/10
54000/54000 [==============================] - 3s 61us/step - loss: 0.1236 - acc: 0.9654
Epoch 8/10
54000/54000 [==============================] - 3s 61us/step - loss: 0.1095 - acc: 0.9692
Epoch 9/10
54000/54000 [==============================] - 3s 63us/step - loss: 0.0982 - acc: 0.9727
Epoch 10/10
54000/54000 [==============================] - 3s 61us/step - loss: 0.0884 - acc: 0.9757
Epoch 1/10
54000/54000 [==============================] - 8s 143us/step - loss: 0.6059 - acc: 0.8570
Epoch 2/10
54000/54000 [==============================] - 3s 61us/step - loss: 0.2730 - acc: 0.9242
Epoch 3/10
54000/54000 [==============================] - 3s 61us/step - loss: 0.2176 - acc: 0.9381
Epoch 4/10
54000/54000 [==============================] - 3s 61us/step - loss: 0.1832 - acc: 0.9476
Epoch 5/1

54000/54000 [==============================] - 8s 151us/step - loss: 0.6185 - acc: 0.8542
Epoch 2/15
54000/54000 [==============================] - 3s 65us/step - loss: 0.2834 - acc: 0.9207
Epoch 3/15
54000/54000 [==============================] - 4s 65us/step - loss: 0.2257 - acc: 0.9362
Epoch 4/15
54000/54000 [==============================] - 3s 65us/step - loss: 0.1895 - acc: 0.9463
Epoch 5/15
54000/54000 [==============================] - 3s 64us/step - loss: 0.1635 - acc: 0.9533
Epoch 6/15
54000/54000 [==============================] - 4s 65us/step - loss: 0.1432 - acc: 0.9594
Epoch 7/15
54000/54000 [==============================] - 4s 65us/step - loss: 0.1268 - acc: 0.9638
Epoch 8/15
54000/54000 [==============================] - 4s 65us/step - loss: 0.1124 - acc: 0.9689
Epoch 9/15
54000/54000 [==============================] - 4s 66us/step - loss: 0.1007 - acc: 0.9723
Epoch 10/15
54000/54000 [==============================] - 3s 65us/step - loss: 0.0909 - acc: 0.9749
Epoch 11/

54000/54000 [==============================] - 4s 66us/step - loss: 0.1251 - acc: 0.9647
Epoch 8/15
54000/54000 [==============================] - 4s 68us/step - loss: 0.1119 - acc: 0.9688
Epoch 9/15
54000/54000 [==============================] - 4s 67us/step - loss: 0.1003 - acc: 0.9726
Epoch 10/15
54000/54000 [==============================] - 4s 67us/step - loss: 0.0912 - acc: 0.9747
Epoch 11/15
54000/54000 [==============================] - 4s 66us/step - loss: 0.0821 - acc: 0.9779
Epoch 12/15
54000/54000 [==============================] - 4s 67us/step - loss: 0.0747 - acc: 0.9797
Epoch 13/15
54000/54000 [==============================] - 4s 66us/step - loss: 0.0680 - acc: 0.9819
Epoch 14/15
54000/54000 [==============================] - 4s 65us/step - loss: 0.0620 - acc: 0.9840
Epoch 15/15
54000/54000 [==============================] - 4s 66us/step - loss: 0.0568 - acc: 0.9851
Epoch 1/15
54000/54000 [==============================] - 8s 155us/step - loss: 0.6205 - acc: 0.8549
Epoc

54000/54000 [==============================] - 4s 65us/step - loss: 0.0473 - acc: 0.9881
Epoch 18/20
54000/54000 [==============================] - 3s 65us/step - loss: 0.0436 - acc: 0.9890
Epoch 19/20
54000/54000 [==============================] - 4s 66us/step - loss: 0.0397 - acc: 0.9905
Epoch 20/20
54000/54000 [==============================] - 4s 65us/step - loss: 0.0364 - acc: 0.9915
Epoch 1/20
54000/54000 [==============================] - 8s 154us/step - loss: 0.5997 - acc: 0.8581
Epoch 2/20
54000/54000 [==============================] - 3s 65us/step - loss: 0.2797 - acc: 0.9213
Epoch 3/20
54000/54000 [==============================] - 3s 65us/step - loss: 0.2233 - acc: 0.9369
Epoch 4/20
54000/54000 [==============================] - 4s 66us/step - loss: 0.1886 - acc: 0.9463
Epoch 5/20
54000/54000 [==============================] - 4s 66us/step - loss: 0.1624 - acc: 0.9536
Epoch 6/20
54000/54000 [==============================] - 4s 65us/step - loss: 0.1425 - acc: 0.9596
Epoch 7

54000/54000 [==============================] - 4s 66us/step - loss: 0.0423 - acc: 0.9899
Epoch 19/20
54000/54000 [==============================] - 4s 65us/step - loss: 0.0389 - acc: 0.9912
Epoch 20/20
54000/54000 [==============================] - 4s 65us/step - loss: 0.0358 - acc: 0.9919
Epoch 1/20
54000/54000 [==============================] - 8s 155us/step - loss: 0.6228 - acc: 0.8532
Epoch 2/20
54000/54000 [==============================] - 4s 66us/step - loss: 0.2803 - acc: 0.9215
Epoch 3/20
54000/54000 [==============================] - 4s 68us/step - loss: 0.2225 - acc: 0.9374
Epoch 4/20
54000/54000 [==============================] - 4s 69us/step - loss: 0.1867 - acc: 0.9468
Epoch 5/20
54000/54000 [==============================] - 4s 67us/step - loss: 0.1602 - acc: 0.9540
Epoch 6/20
54000/54000 [==============================] - 4s 67us/step - loss: 0.1400 - acc: 0.9606
Epoch 7/20
54000/54000 [==============================] - 4s 68us/step - loss: 0.1240 - acc: 0.9653
Epoch 8/

60000/60000 [==============================] - 8s 129us/step - loss: 0.0185 - acc: 0.9967
Epoch 20/20
60000/60000 [==============================] - 8s 130us/step - loss: 0.0162 - acc: 0.9975


In [103]:
#finding out the best batch_size and best number of epschs
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))

Best: -0.087825 using {'batch_size': 50, 'epochs': 20}


Best Batch Size and Epochs is 50 and 20 respectively

Obtain the accuracy from the Best estimate against the training set

In [117]:
score = grid.best_estimator_.model.evaluate(X_test, y_test)

10000/10000 [==============================] - 3s 285us/step


Printing out the score

In [118]:
#score[0] would be the neg log loss
print("Score: " + str(score[1]))

Score: 0.9772
